_name_: compression
d_model: 256
chunk_len: 392
num_special_tokens: 1
model:
  _name_: model
  prenorm: true
  transposed: false
  n_layers: 4
  layer:
    - _name_: mha
      causal: true
      n_heads: 8
      dropout: null
      bias: True
      add_bias_kv: False
      add_zero_attn: False
      kdim: null
      vdim: null
    - _name_: ff
      expand: 4
      activation: gelu
      dropout: ${...dropout} # Same as null
  d_model: 256
  residual: R
  pool:
    _name_: pool
    stride: 1
    expand: null
  norm: layer
  dropout: 0.0
  tie_dropout: false
  track_norms: true

encoder:
  _name_: position